# Site settings
title: Osprey
author: VoProVols
email:
description: An advanced UI and assignment algorithm for robust voter-protection programs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://voprovols.github.io/"

# User setting
owner: VoProVols
email:
telephone:
copyright: Osprey Campaign Solutions, Inc.

# API settings
google_api_key:

# Build settings
markdown: kramdown
